- apt:
    name: apache2
    state: present

- copy:
    dest: "/etc/apache2/sites-available/example.com.conf"
    src: "example.com.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart apache2

- file:
    src: /etc/apache2/sites-available/example.com.conf
    dest: /etc/apache2/sites-enabled/example.com.conf
    owner: root
    group: root
    state: link
  notify: restart apache2
